### ISSUE TITLE
Request permission for checkpoint unitr_pretrain.

### ISSUE THREAD

**Issue by synsin0** [Haiyang-W/UniTR#3] opened 2023-09-22 03:18 UTC
Thanks for your great work! It seems that you set permission on the pretrained checkpoint, may you open the permission for downloading? By the way, may you explain details about how the pretrained models are converted? From DSVT I may guess or from which image backbone or both?

**Comment by Haiyang-W** [comment] 2023-09-22 04:13
Sorry for that, we will update the pre-trained weights.

We self-pretrain the unitr-image branch on ImageNet.

**Comment by Haiyang-W** [comment] 2023-09-22 04:57
The Google Drive link is updated. 

By the way,  could you mention it in this issue if you can reproduce the same performance easily?
Your double-check will be important to us and helpful to others who use this code. :)

Thanks!

Best,
Haiyang

**Comment by synsin0** [comment] 2023-09-22 05:10
Okay, I will reproduce the training process as the instructions says. Considers the preprocessing and training time cost. I will report two or three days later to see if the eval goes normally.

**Comment by Haiyang-W** [comment] 2023-09-22 05:20
Thanks a lot! If you have any problems, please feel free to let me know. 

Notably, we observed that the fluctuation of NuScenes on our unitr is relatively large, and the NDS of Unitr+LSS is between 72.8 and 73.3. The performance reported is the best among the three times.  We also provide the best-performing model parameters and logs.

Hope everything goes well with you. :)

Best,
Haiyang

**Comment by Haiyang-W** [comment] 2023-09-22 05:33
Here is the referenced training cost, which could be of assistance to you.

The overall training time of UniTR+LSS is 24h on 8 A100 GPUs(40GB) with shared memory (gt sampling) and closed torch checkpoints [here set to [ ]](https://github.com/Haiyang-W/UniTR/blob/f3266f1831c251eda0d2a84721bc43fbd0cc4b5a/tools/cfgs/nuscenes_models/unitr%2Blss.yaml#L125). Enabling the torch checkpoints will extend the training time by an hour. We haven't experimented with the version that doesn't share memory of gt sampling, so we're unable to provide a reference cost regarding this variant.

**Comment by Haiyang-W** [comment] 2023-09-22 05:38
If you have any questions, please feel free to let us know. We will improve and update this code based on your feedback to make it more user-friendly and provide a better experience for everyone.

**Comment by synsin0** [comment] 2023-09-23 10:02
Well, I encoutered a problem at the end of pre-processing, which is , Ran out of memory for RAM=120G in my environment. The gt_database creation process costs too much memory. I'd like to confirm the size of two files. I see in my environment , nuscenes_10sweeps_withvelo_lidar.npy = 12G, is that true, may you check the file size to see if mine is correctly generated.

**Comment by Haiyang-W** [comment] 2023-09-23 11:26
> Well, I encoutered a problem at the end of pre-processing, which is , Ran out of memory for RAM=120G in my environment. The gt_database creation process costs too much memory. I'd like to confirm the size of two files. I see in my environment , nuscenes_10sweeps_withvelo_lidar.npy = 12G, is that true, may you check the file size to see if mine is correctly generated.

- This 12GB is correct; it may vary on different machines and environments. In my case, some machines have 12GB, and some have 24GB. I believe that 12GB should be fine. 

- However, when enabling 'share mem,' it does require a significant amount of memory. I have 256GB of RAM on my end. Regarding your question, I would recommend using a machine with sufficient memory to generate the 'share mem' file because training is faster with it, and all of our experiments have 'share mem' enabled. However, turning off 'share mem' should also be fine, and that way, you won't have any memory issues.

**Comment by Haiyang-W** [comment] 2023-09-23 11:35
> Well, I encoutered a problem at the end of pre-processing, which is , Ran out of memory for RAM=120G in my environment. The gt_database creation process costs too much memory. I'd like to confirm the size of two files. I see in my environment , nuscenes_10sweeps_withvelo_lidar.npy = 12G, is that true, may you check the file size to see if mine is correctly generated.

If you feel it's necessary, you can email me and then add me on WeChat, so we can have a more convenient way to contact and resolve issues.

My email is wanghaiyang6@stu.pku.edu.cn

**Comment by synsin0** [comment] 2023-09-26 02:09
My reproduced results for the default unitr.yaml without any modification is: mAP:	 0.6958 NDS:	 0.7269. The result is 0.5% slightly lower than yours best. My training log is provided as follows:
[train_20230924-190858.log](https://github.com/Haiyang-W/UniTR/files/12721278/train_20230924-190858.log)

**Comment by Haiyang-W** [comment] 2023-09-26 05:53
Thank you very much for your prompt response. Based on your results, our code should be fine.

I think these results to be reasonably sound; we conducted the experiment thrice and selected the highest score. 
The performance of unitr we provided is `73.0 NDS` and `70.1 mAP`, your result is `72.7 NDS` and `69.6 mAP`.

The NDS scores across the three runs were 72.6, 73.0, and 72.9 for unitr.yaml without LSS. Notably, there is still a significant fluctuation in the NuScenes dataset, particularly in the mAP metric, where fluctuations are even more pronounced. 

Additionally, we have also provided checkpoints for you to verify on your end to ensure consistent evaluation with ours. 
Switching to the LSS version can lead to an improvement of 0.3 to 0.5 points.

Thank you once again for your prompt response and for helping us validate the correctness of our code.
I hope UNITR can be helpful for your future research. Wishing you all the best.

Haiyang,

**Comment by Haiyang-W** [comment] 2023-09-26 05:56
This issue will be closed as it appears to have been resolved. If you have any further questions, please feel free to ask.

**Closed by Haiyang-W** 2023-09-26 05:56 UTC

**Comment by Looottch** [comment] 2023-11-28 09:47
> The Google Drive link is updated.
> 
> By the way, could you mention it in this issue if you can reproduce the same performance easily? We have checked the code in our workspace. However, your double-check will be important to us and helpful to others who use this code. :)
> 
> Thanks!
> 
> Best, Haiyang

link of google drive is gone, would you mind put a new link here

**Comment by Haiyang-W** [comment] 2023-11-29 03:18
> > The Google Drive link is updated.
> > By the way, could you mention it in this issue if you can reproduce the same performance easily? We have checked the code in our workspace. However, your double-check will be important to us and helpful to others who use this code. :)
> > Thanks!
> > Best, Haiyang
> 
> link of google drive is gone, would you mind put a new link here

Can you tell me which link is missing? Everything I checked seems to be working.

**Comment by Looottch** [comment] 2023-11-29 11:02
> > > The Google Drive link is updated.
> > > By the way, could you mention it in this issue if you can reproduce the same performance easily? We have checked the code in our workspace. However, your double-check will be important to us and helpful to others who use this code. :)
> > > Thanks!
> > > Best, Haiyang
> > 
> > 
> > link of google drive is gone, would you mind put a new link here
> 
> Can you tell me which link is missing? Everything I checked seems to be working.

ckpt of Bev Map Segmentation in the following pic
![image](https://github.com/Haiyang-W/UniTR/assets/42186852/4fef903e-5267-4807-b1f2-88d903e5ba43)

**Comment by nnnth** [comment] 2023-11-30 16:10
I checked my sharing permissions and there seems to be no problem, can you show us what happens after clicking the link?
<img width="504" alt="截屏2023-12-01 上午12 10 04" src="https://github.com/Haiyang-W/UniTR/assets/49348353/4208db20-4dfa-40f5-9758-6d4d4eca4db9">

**Comment by Looottch** [comment] 2023-12-13 01:56
> I checked my sharing permissions and there seems to be no problem, can you show us what happens after clicking the link? <img alt="截屏2023-12-01 上午12 10 04" width="504" src="https://private-user-images.githubusercontent.com/49348353/286993803-4208db20-4dfa-40f5-9758-6d4d4eca4db9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzI4NTQsIm5iZiI6MTcwMjQzMjU1NCwicGF0aCI6Ii80OTM0ODM1My8yODY5OTM4MDMtNDIwOGRiMjAtNGRmYS00MGY1LTk3NTgtNmQ0ZDRlY2E0ZGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDAxNTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNTM4MzdiMWI5Njk5NDgyOTEzMGU4ZTNkY2IyMGNiY2E3OTVmYTZjNjFmN2Q4MzhkZmI4ZTA4MjYyMTRiY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wJG4EET5hZrdNtYECTQHotKwlK1NUo3kLKe8e1zhYy0">

like this, (maybe u moved to other folder?
![image](https://github.com/Haiyang-W/UniTR/assets/42186852/92f0739b-d3a9-4869-abca-9a53e48c54c7)

**Comment by nnnth** [comment] 2023-12-13 07:16
I asked other people to try clicking this link and they had no problem. Maybe you need to change the network, browser, device, or ask someone else to download it for you.

**Comment by Haiyang-W** [comment] 2023-12-14 09:43
> > I checked my sharing permissions and there seems to be no problem, can you show us what happens after clicking the link? <img alt="截屏2023-12-01 上午12 10 04" width="504" src="https://private-user-images.githubusercontent.com/49348353/286993803-4208db20-4dfa-40f5-9758-6d4d4eca4db9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzI4NTQsIm5iZiI6MTcwMjQzMjU1NCwicGF0aCI6Ii80OTM0ODM1My8yODY5OTM4MDMtNDIwOGRiMjAtNGRmYS00MGY1LTk3NTgtNmQ0ZDRlY2E0ZGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDAxNTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNTM4MzdiMWI5Njk5NDgyOTEzMGU4ZTNkY2IyMGNiY2E3OTVmYTZjNjFmN2Q4MzhkZmI4ZTA4MjYyMTRiY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wJG4EET5hZrdNtYECTQHotKwlK1NUo3kLKe8e1zhYy0">
> 
> like this, (maybe u moved to other folder? ![image](https://private-user-images.githubusercontent.com/42186852/290051314-92f0739b-d3a9-4869-abca-9a53e48c54c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDcxNjMsIm5iZiI6MTcwMjU0Njg2MywicGF0aCI6Ii80MjE4Njg1Mi8yOTAwNTEzMTQtOTJmMDczOWItZDNhOS00ODY5LWFiY2EtOWE1M2U0OGM1NGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA5NDEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYjljNGQ5ZDI5ZTdiZjUxMjdmNTc1ODVlNGY1YTVmNTAxZDc0NmQ0MzEyYTdjMjg2NDE1NDdmMTEwZWZlNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S_2NRvnFXZ7-O9-ZCyj60oUR6btF7kiZPAEwj0o26ts)

I think it might be an issue with your internet connection, for example, if you are in mainland China, Google Drive requires using a VPN.
